DiplomProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("main.urls")),
]

urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from .views import *

app_name = "main"
urlpatterns = [
    path("", HomeView.as_view(), name = "home"),
    path("contact-us/", ContactView.as_view(), name = "contact"),
    path("types/",TypesView.as_view(), name = "types"),
    path("pet/<int:pk>/", PetDetailView.as_view(), name ="petdetail"),
    path("volunteer/", VolunteerView.as_view(), name = "volunteer"),
    path("basket-<int:pet_id>/",BasketView.as_view(), name = "basket"),
    path("my-basket/", MyBasketView.as_view(), name = "mybasket"),
    path("manage-basket/<int:b_id>/", ManageBasketView.as_view(), name="managebasket"),
    path("register/", UserRegistrationView.as_view(), name="userregistration"),
    path("login/", UserLoginView.as_view(), name = "userlogin"),
    path("logout/", UserLogoutView.as_view(), name = "userlogout"),
    path("home/<int:pk>/add/", PetCreateView.as_view(), name = "petcreate"),
    path("pets/<int:td>/", FilterView.as_view(), name = "filter" ),
    path("forgot-password/", PasswordForgotView.as_view(), name = "forgotpassword"),
    path("reset-password/<email>/<token>/", ResetPasswordView.as_view(), name = "resetpassword"),
    path("profile/<int:pk>/pets/", MyPetView.as_view(), name = "petsbyuser"),
    path("manage-pets/<int:p_pk>/", ManagePetView.as_view(), name = "managepet"),
    path("profile/<int:pk>", ProfileView.as_view(), name = "profile"),
    path("profile/edit/<int:pk>/", ProfileEditView.as_view(), name = "editprofile"),
    path("pet/edit/<int:pk>/", PetEditView.as_view(), name = "editpet"),

]

main/models.py
from django.db import models
from django.contrib.auth.models import User

class UserC(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=300)
    last_name = models.CharField(max_length=300)
    email = models.EmailField()
    phone = models.CharField(max_length=18)
    joined_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.first_name +" " + self.last_name

# Type
class Type(models.Model):
    name = models.CharField(max_length=300)
    image = models.ImageField(upload_to="pet_imgs/")

    def __str__(self):
        return self.name

# Breed
class Breed(models.Model):
    type = models.ForeignKey(Type, on_delete=models.CASCADE)
    name = models.CharField(max_length=300)

    def __str__(self):
        return self.name

class City(models.Model):
    name = models.CharField(max_length=300)
    class Meta:
        verbose_name = "City"
        verbose_name_plural = "Cities"

    def __str__(self):
        return self.name

# Gender of pet
class Gender(models.Model):
    name = models.CharField(max_length=2)

    def __str__(self):
        return self.name

# Pet
class Pet(models.Model):
    name = models.CharField(max_length=300)
    price = models.PositiveIntegerField()
    gender = models.ForeignKey(Gender, on_delete=models.CASCADE)
    birthday_date = models.DateField()
    city = models.ForeignKey(City, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="pet_imgs/")
    comment = models.TextField()
    type = models.ForeignKey(Type, on_delete=models.CASCADE)
    breed = models.ForeignKey(Breed, on_delete=models.CASCADE)

    def __delete__(self, instance):
        return self.breed

class PetsByUser(models.Model):
    user = models.ForeignKey(UserC, on_delete=models.CASCADE)
    pet = models.ForeignKey(Pet, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.email + " added "+self.pet.name

# Image
class PetImage(models.Model):
    pet = models.ForeignKey(Pet, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="pet/images/")

    def __str__(self):
        return self.pet.name

# Cart
class Cart(models.Model):
    user =models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    total = models.PositiveIntegerField(default=0)
    created_at =models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "Cart: " +str(self.id)

# Basket
class Basket(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    pet = models.ForeignKey(Pet, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField()
    subtotal = models.PositiveIntegerField()

    def __str__(self):
        return "Cart: " + str(self.cart.id) + "Basket: " + str(self.id)

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" charset="width=device-width, initial-scale=1.0">
    <title>Home</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body>
    <div class="container" style="background-color: rgb(250,250,250)">
        <nav class="navbar navbar-expand-lg navbar-light bg-light " >
            <a class="navbar-brand" href="{% url 'main:home' %}">Online Pet Shop</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'main:home' %}">Главная<span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'main:volunteer' %}">Волонтеры</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'main:mybasket' %}">🛒 Избранное </a>
                    </li>
                    {% if request.user.userc %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'main:petcreate' user.userc.pk %}">+ Подать объявление</a>
                        </li>
                    {% else%}
                       <li class="nav-item">
                            <a class="nav-link" href="{% url 'main:userlogin' %}">+ Подать объявление</a
                       </li>
                    {% endif %}
                </ul>
                <ul class="navbar-nav navbar-right">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
                            aria-haspopup="true" aria-expanded="false">Мой аккаунт</a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        {% if request.user.userc %}
                            <a class="dropdown-item" href="{% url 'main:profile' user.userc.pk %}">Личный кабинет</a>
                            <a class="dropdown-item" href="{% url 'main:userlogout' %}">Выход</a>
                        {% else %}
                            <a class="dropdown-item" href="{% url 'main:userregistration' %}">Регистрация</a>
                            <a class="dropdown-item" href="{% url 'main:userlogin' %}">Bxoд</a>
                        {% endif %}
                        </div>
                    </li>
                </ul>
            </div>
        </nav>
        <hr>
    </div>

    {% block content %}
    {% endblock %}
    {% block footer %}
    {% endblock %}
    <br>

    <footer class="container" style="text-align: center; position: relative; height: 100px; bottom: 0; left: 0; right: 0; background: rgb(250,250,250); padding: 1rem">
        <hr style="bottom: auto">
        <a href="/contact-us/" style="right: auto">Служба заботы</a>
        <p>Student of KBTU 2022</p>
    </footer>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
            integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
            crossorigin="anonymous"></script>

    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
            integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
            crossorigin="anonymous"></script>

    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
            integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
            crossorigin="anonymous"></script>
</body>
</html>

templates/basket.html
{% extends 'base.html' %}
{% block title %} Basket {% endblock %}
{% block content %}

<div class ="container">
    <h3>Успешно  добавлено</h3>
</div>



{% endblock %}

templates/contactus.html
{% extends 'base.html' %}
{% block content %}
    <div class="container">
        <p>Напишите нам<br>
            Вы можете обратиться в службу заботы о пользователях с 9:00 до 20:00 в рабочие
            и с 9:00 до 17:00 в выходные дни. <br>
            Будем благодарны за найденные ошибки и предложения о добавлении категорий, которых вам не хватает. Спасибо!
        </p>
        <h5>Контакты :</h5>
        <h6>Телефор: +7 (700) 320 32 34</h6>
        <h6>Почта: onlinepetshop@mail.ru </h6>
        <img src="https://onkostrahovanie.ru/wp-content/uploads/2021/06/mm1.svg" style="text-align: center" >

    </div>

{% endblock %}

templates/editpet.html
{% extends 'base.html' %}
{% block title %} Edit Pet {% endblock %}
{% block content %}
   {% if request.user.userc %}
    <div class = "container">
        <h3>Редактировать объявление</h3>
        <hr/>
        <div class = "clearable-file-input" style="background-color: bisque ">
            <form action="" method="GET">
                Цена: <br>
                <input type="number" name="price" placeholder="{{ edit_pet.price }}">
                <br>
                Город: <br>
                <select name="city" placeholder="{{ edit_pet.city }}">
                        <option>-</option>
                        {% for c in cities %}
                        <option>{{ c }}</option>
                        {% endfor %}

                </select>
                <br>
                Описание:
                <br>
                <textarea  type="text" name="comment" style="height: 240px; width: 440px">
                    {{ edit_pet.comment }}
                </textarea>
            <br>
                <a href="reverce"><button type="submit" style="position: center">Сохранить</button></a>
            </form>
        </div>
    </div>
    {% endif %}
{% endblock %}

templates/editprofile.html
{% extends 'base.html' %}
{% block title %} Edit Profile {% endblock %}
{% block content %}
   {% if request.user.userc %}
    <div class = "container">
        <h3> Edit Profile</h3>
        <hr/>
        <div class = "clearable-file-input" style="background-color: bisque ">
            <form action="" method="GET">
                Логин: <br>
                <input type="text" name="username" placeholder="{{ user.username }}">
                <br>
                Почта: <br>
                <input type="text" name="email" placeholder="{{ user.email }}">
                <br>
                Пароль:
                <br>
                <input type="text" name="password" placeholder=" *** ">
            <br>
            <button type="submit" style="position: center">Сохранить</button>
            </form>
        </div>
    </div>
    {% endif %}
{% endblock %}

templates/home.html
{% extends 'base.html' %}
{% block content %}
<div class ="container">


    <div class = "row mt-3">
        {% for type in types %}
        <div class = "col-md-3">
            <div class = "m-2">
                <h4><a href="{% url 'main:filter' type.pk %}">{{ type.name }}</a></h4>
                <img src="{{ type.image.url }}" alt="" class ="img-fluid" style="height:130px; width: 100%; object-fit: contain" >

            </div>
        </div>
        {% endfor %}
    </div>
    <hr>
    <div class = "row mt-3">
        {% for p in pet_list %}
        <div class = "col-md-3 card">
        <div class = "m-2">
            <h4><a href="{% url 'main:petdetail' p.pk %}">{{ p.name }}</a></h4>
            <img src="{{ p.image.url }}" class="img-fluid" alt="" style="object-fit:contain; height: 200px;  width: 100%">
            <p class="mt-3">Цена: {{ p.price }} тг</p>
            <p class="mt-3">Пол: {{ p.gender }} &emsp;
{#            <a href="{% url 'main:basket' p.id %}" target="_blank" class="btn btn-primary" >💚</a>#}
             <a href=" {%url 'main:basket' p.id %} " target="_blank" class="btn btn-primary">Добавить 🛒</a>
            </p>
            </div>
        </div>
        {% endfor %}


    </div>
    <nav aria-label="..." style="position: center">
        <ul class="pagination">
            {% if pet_list.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page={{ pet_list.previous_page_number }}">Предыдущая</a>
              </li>
            {% else %}
            <li class="page-item disabled">
                <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Предыдущая</a>
            </li>
            {% endif %}

            {% for i in pet_list.paginator.page_range %}
            {% if i == pet_list.number %}
            <li class="page-item active"><a class="page-link">{{i}}</a></li>
            {% else %}
            <li class="page-item"><a class="page-link" href="?page={{i}}">{{i}}</a></li>
            {% endif %}
            {% endfor %}

            {% if pet_list.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ pet_list.next_page_number }}">Следующая</a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Следующая</a>
            </li>
            {% endif %}
        </ul>
      </nav>

</div>
{% endblock %}

templates/messages.html
{% if messages %}
  {% for message in messages %}
    <div class="alert {{ message.tags }} alert-dismissible" role = "alert">
     <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">×</span>
    </button>
      {{message}}
{#    <a href="{% url 'main:basket' pet_id%}" class="del-msg">&times;</a>#}

    </div>
 {% endfor %}
{% endif %}

templates/mybasket.html
{% extends 'base.html' %}
{% block content %}
<div class ="container">

    <h1 class ="text-center">Избранное</h1>
    <hr>
    <div class = "row mt-3">
        {% for b in cart.basket_set.all %}
        <div class = "col-md-3 card">
        <div class = "m-2">
            <h4><a href="{% url 'main:petdetail' b.pet.pk %}">{{ b.pet.name }}</a>
            </h4>
            <img src="{{ b.pet.image.url }}" alt="" class="img-fluid" style="object-fit:contain; height: 200px; width: 100%; position: center; ">
            <p class="mt-3">Цена: {{ b.pet.price }} тг</p>
            <p class="mt-3">Пол: {{ b.pet.gender    }} &emsp; &emsp;
                <a href="{% url 'main:managebasket' b.id %}?action=rmv" class="btn btn-danger" style="text-align: right">&times</a>
            </p>



            </div>
        </div>
        {% endfor %}


    </div>
</div>
{% endblock %}

templates/petcreate.html
{% extends 'base.html' %}
{% block title %} Add New Pet {% endblock %}
{%  block content %}
<div class="container">
    <div class="row">
        <div class="col-md-10 mx-auto">
            <h3>Добавить объявление</h3>
            <hr>
            <form action="" method="post" enctype="multipart/form-data" >
                {% csrf_token %}
                {{ form.as_p }}
                <button class = "btn btn-primary">Загрузить данные</button>
            </form>
        </div>

    </div>

</div>
{% endblock %}

templates/resetpassword.html
{% extends 'base.html' %}

{% block title %}Reset password{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-8">
            <form action="" method="POST">
                {% csrf_token %}
                {{form.as_p}}
                <button>Восстановить</button>
            </form>
        </div>
    </div>
</div>

{% endblock %}

templates/types.html
{% extends 'base.html' %}
{% block content %}

<div class ="container">

    <h1 class ="text-center">Welcome to our website</h1>
    <hr>
    <div class = "row mt-3">
        {% for type in types %}
        <div class = "col-md-3">
            <div class = "m-2">
                <h4><a href="[name = 'home']">{{ type.name }}</a></h4>
                <img src="{{ type.image.url }}" alt="" class ="img-fluid" style="height:2500" oject-fit:cover>
            </div>
        </div>
        {% endfor %}
    </div>
</div>


{% endblock %}

templates/userlogin.html
{% extends 'base.html' %}

{% block title %} User Login {% endblock %}
{% block content %}
<div class="container">
    <div class="row mt-3">
        <div class="col-md-6 max-auto">
            <h3 class = "text-center"> Войти</h3><hr>
            <form action="" method="POST">
                {% csrf_token %}
                {{ form.as_p }}
                &ensp; &emsp; &emsp; &emsp; <button class="btn btn-primary">Войти</button>
                <a href="{% url 'main:forgotpassword' %}">Забыли пароль?</a>
                {% if error %}
                    <li style="color: red" >{{ error }}</li>
                {% endif %}
            </form>
        </div>
    </div>

</div>
{% endblock %}

templates/userregistration.html
{% extends 'base.html' %}

{% block title %} User Registration {% endblock %}
{% block content %}
<style>
    .errorlist{
        color:red
    }
</style>
<div class="container">
    <div class="row mt-3">
        <div class="col-md-6 max-auto">
            <h3 class = "text-center"> Регистрация пользователя</h3><hr>
            <form action="" method="POST">
                {% csrf_token %}
                {{ form.as_p }}
                <button class="btn btn-primary">Регистрировать</button>
            </form>
        </div>
    </div>

</div>
{% endblock %}

templates/volunteer.html
{% extends 'base.html' %}
{% block title %}Волонтеры{% endblock %}
{% block content %}
    <div class="container">
        <div class="col-md-12">

            <h2 align="center">Волонтеры</h2>
            <hr>
            <h4>Алматы</h4>
            <h4> Фонд «КотоПес»</h4>
{#            <div class="row">#}
{#                <div class="col-md-6">#}
                <img src="https://kotopesoff.kz/wp-content/uploads/2015/01/5QF19byIYFI-580x390.jpg" alt="" class="img-fluid">
{#             </div>#}
{#            <div class="col-md-6">#}
                <p>Общественный Фонд «Котопес» был создан в 2011 г. усилиями нескольких человек и существует исключительно на благотворительные взносы. Основной деятельностью фонда является спасение, лечение и социализация бездомных животных, а также поиск хозяев для них. За это время мы добились немалых успехов: было спасено более 3000 животных, почти каждый из которых обрел новую семью.

                <br> <em>Проблема численности бездомных животных</em> – это проблема не животных, а людей! Всем известно, что бездомные животные могут стать источником опасных заболеваний (например, бешенства). Также не является секретом то, что службы, занимающиеся отловом и истреблением бездомных животных, абсолютно не влияют на их численность. То есть, их работа – неэффективна! Количество бездомных животных не просто не уменьшается, а увеличивается!

                <br><strong>Чем помочь приюту:</strong> Ежедневно фонду нужна помощь волонтеров, транспорт и временные дома для животных. Также корма для животных, лекарства и помощь по оплате долгов в ветеринарных клиниках. </p>

                <h4>Контакты: +7 702 262 39 82</h4><hr>
{#            </div>#}
{#        </div><hr>#}
            <h4> Фонд «KARE-Забота»</h4>
            <img src="https://kare-zabota.kz/wp-content/uploads/2016/11/No-name-1-7-770x335.jpg" class="img-fluid">
            <p>Казахстанский общественный фонд защиты животных "KARE-Забота" (KARE) – это первая официальная зоозащитная организация, ведущая информационно-образовательную деятельность на территории Республики Казахстан, направленную на формирование ответственного отношения к животным.

Фонд был создан инициативной группой в июне 2008 года и уже в первый год существования объединил сотни неравнодушных людей.

Фонд является членом Всемирного общества защиты животных (WSPA – World Society for the Protection of Animals) .

Все сотрудники KARE работают на волонтерской основе.</p>
            <h4>Контакты: +7 707 877 94 41</h4><hr>
        </div>
    </div>
{% endblock %}